# Generated by Django 3.1.6 on 2021-06-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210613_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='details',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
