# Generated by Django 3.1.6 on 2021-06-13 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_submission_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submit_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
