# Generated by Django 3.1.6 on 2021-03-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210302_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='agrees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='disagrees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='strongs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='weaks',
            field=models.IntegerField(default=0),
        ),
    ]
