# Generated by Django 3.1.6 on 2021-03-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210302_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='disagrees',
            new_name='agreechecks',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='weaks',
            new_name='strongchecks',
        ),
    ]
