# Generated by Django 3.1.6 on 2021-06-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_submission_submit_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='earned_points',
        ),
    ]
