# Generated by Django 3.1.6 on 2021-06-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20210613_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='feedback',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
