# Generated by Django 3.1.6 on 2021-03-03 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0006_auto_20210302_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed', models.ManyToManyField(related_name='agreed', to='forum.Post')),
                ('stronged', models.ManyToManyField(related_name='stronged', to='forum.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewed', models.ManyToManyField(related_name='viewed', to='forum.Post')),
            ],
        ),
    ]
