# Generated by Django 3.1.6 on 2021-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_userwrapper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwrapper',
            name='agreed',
            field=models.ManyToManyField(blank=True, related_name='agreed', to='forum.Post'),
        ),
        migrations.AlterField(
            model_name='userwrapper',
            name='stronged',
            field=models.ManyToManyField(blank=True, related_name='stronged', to='forum.Post'),
        ),
        migrations.AlterField(
            model_name='userwrapper',
            name='viewed',
            field=models.ManyToManyField(blank=True, related_name='viewed', to='forum.Post'),
        ),
    ]
