# Generated by Django 3.1.6 on 2021-06-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_grade_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='earned_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
