# Generated by Django 3.1.6 on 2021-03-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20210303_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwrapper',
            name='disagreed',
            field=models.ManyToManyField(blank=True, related_name='disagreed', to='forum.Post'),
        ),
        migrations.AddField(
            model_name='userwrapper',
            name='weaked',
            field=models.ManyToManyField(blank=True, related_name='weaked', to='forum.Post'),
        ),
    ]
