# Generated by Django 3.1.6 on 2021-07-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20210613_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_of_course', to='forum.course'),
        ),
        migrations.CreateModel(
            name='AssignmentGrouping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.course')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='grouping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_of_grouping', to='forum.assignmentgrouping'),
        ),
        migrations.AddConstraint(
            model_name='assignmentgrouping',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='unique name'),
        ),
    ]
