# Generated by Django 3.1.6 on 2021-07-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20210709_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignmentGrouping',
            new_name='AssignmentModule',
        ),
    ]
