# Generated by Django 3.1.6 on 2021-08-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20210709_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['end_datetime']},
        ),
    ]
