# Generated by Django 3.1.6 on 2021-08-25 04:16

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20210823_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
