# Generated by Django 3.1.6 on 2021-08-26 20:45

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20210824_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_of_module', to='forum.assignmentmodule'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='details',
            field=django_quill.fields.QuillField(),
        ),
    ]
