# Generated by Django 3.1.6 on 2021-09-06 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0017_course_coteachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coteachers',
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinnedcourses', models.ManyToManyField(blank=True, related_name='pinnedcourses_of_student', to='forum.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdata_of_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
