# Generated by Django 3.1.6 on 2021-09-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_auto_20210906_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='pinnedcourses',
            field=models.ManyToManyField(blank=True, related_name='pinnedcourses_of_course', to='forum.Course'),
        ),
    ]
