# Generated by Django 3.1.6 on 2021-09-06 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0019_auto_20210906_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='pinnedcourses',
            field=models.ManyToManyField(blank=True, related_name='pinnedcourses_of_user', to='forum.Course'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdata_of_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
