# Generated by Django 3.1.6 on 2021-09-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_auto_20210906_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='student',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='pinnedcourses',
            field=models.ManyToManyField(blank=True, related_name='userdata_of_pinnedcourse', to='forum.Course'),
        ),
    ]
