# Generated by Django 3.1.6 on 2021-09-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0022_auto_20210906_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['end_datetime', 'title']},
        ),
    ]
